# Generated by Django 5.1.4 on 2025-03-27 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
        ('Order', '0007_orderitem_promotion_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesfunnel',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'Мобильный'), ('desktop', 'Десктоп'), ('tablet', 'Планшет')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesfunnel',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.orderitem'),
        ),
        migrations.AlterField(
            model_name='salesfunnel',
            name='stage',
            field=models.CharField(choices=[('view', 'Просмотр'), ('cart', 'Корзина'), ('checkout', 'Оформление'), ('payment', 'Оплата')], max_length=20),
        ),
    ]
