# Generated by Django 5.1.4 on 2025-03-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0004_alter_productperformance_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentanalysis',
            name='gateway_performance',
        ),
        migrations.AddField(
            model_name='orderanalytics',
            name='time_performance',
            field=models.FloatField(default=1, help_text='Время обработки в секундах'),
        ),
    ]
