# Generated by Django 5.1.4 on 2025-03-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dilivery_status',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
