# Generated by Django 5.1.4 on 2025-03-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_dilivery_status'),
        ('Payment', '0002_alter_payment_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=512)),
            ],
            options={
                'verbose_name': 'Канал продаж',
                'verbose_name_plural': 'Каналы продаж',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='chanell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.saleschannel'),
        ),
    ]
