# Generated by Django 5.1.4 on 2025-03-31 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_rename_quantity_orderitem_quanity_and_more'),
        ('Product', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='Product.product'),
        ),
    ]
