# Generated by Django 5.1.4 on 2025-04-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(blank=True, default=1.0),
        ),
    ]
