# Generated by Django 5.1.4 on 2025-01-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSecurity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
