# Generated by Django 5.1.4 on 2025-01-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSecurity', '0002_alter_auditlog_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Аудит', 'verbose_name_plural': 'Аудиты'},
        ),
    ]
