# Generated by Django 5.1.8 on 2025-11-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSecurity', '0004_alter_auditlog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_string', models.CharField(max_length=2048)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ошибка',
                'verbose_name_plural': 'Ошибки',
            },
        ),
    ]
