# Generated by Django 5.1.8 on 2025-10-30 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_alter_pagetext_options'),
        ('Product', '0010_product_type_subscription_usersubcription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buttons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('template_id', models.IntegerField()),
                ('action', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Кнопка на странице',
                'verbose_name_plural': 'Кнопки на страницах',
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('template_id', models.IntegerField()),
                ('buttons', models.JSONField()),
            ],
            options={
                'verbose_name': 'Настройки футера',
            },
        ),
        migrations.CreateModel(
            name='NavBarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.JSONField()),
                ('template_id', models.IntegerField()),
                ('buttons', models.JSONField()),
            ],
            options={
                'verbose_name': 'Настройки навигационной панели',
            },
        ),
        migrations.CreateModel(
            name='PageColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('page_name', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Цвет на странице',
                'verbose_name_plural': 'Цвета на страницах',
            },
        ),
        migrations.AddField(
            model_name='pagetext',
            name='template_id',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField()),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='Product.product')),
            ],
            options={
                'verbose_name': 'Карточка товара',
                'verbose_name_plural': 'Карточки товаров',
            },
        ),
    ]
