# Generated by Django 5.1.4 on 2025-01-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_rename_password_user_base_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
