# Generated by Django 5.1.4 on 2025-03-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_usergroup_options_usergroup_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addres',
            new_name='addresss',
        ),
    ]
