# Generated by Django 5.1.4 on 2025-03-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_alter_salesfunnel_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesfunnel',
            name='device_type',
            field=models.CharField(blank=True, choices=[('mobile', 'Мобильный'), ('desktop', 'Десктоп'), ('tablet', 'Планшет')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesfunnel',
            name='stage',
            field=models.CharField(choices=[('view', 'Просмотр'), ('cart', 'Корзина'), ('checkout', 'Оформление'), ('payment', 'Оплата'), ('delivery', 'Доставка')], max_length=20),
        ),
    ]
