# Generated by Django 5.1.4 on 2025-03-30 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0003_alter_salesfunnel_device_type_and_more'),
        ('Product', '0007_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productperformance',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='Product.product'),
        ),
        migrations.AlterField(
            model_name='salesfunnel',
            name='session_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
