# Generated by Django 5.1.4 on 2025-04-01 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0006_alter_cohortanalysis_options_and_more'),
        ('Payment', '0006_alter_payment_processed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentanalysis',
            options={'verbose_name': 'Анализ платежа', 'verbose_name_plural': 'Анализы платежей'},
        ),
        migrations.AddField(
            model_name='paymentanalysis',
            name='analysis_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Время проведения анализа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentanalysis',
            name='gateway_performance',
            field=models.FloatField(help_text='Время обработки в секундах', null=True),
        ),
        migrations.AlterField(
            model_name='paymentanalysis',
            name='chargeback_probability',
            field=models.FloatField(help_text='Вероятность возврата платежа (%)', null=True),
        ),
        migrations.AlterField(
            model_name='paymentanalysis',
            name='fraud_indicators',
            field=models.JSONField(default=dict, help_text='Флаги рисков мошенничества'),
        ),
        migrations.AlterField(
            model_name='paymentanalysis',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='Payment.payment'),
        ),
        migrations.AlterField(
            model_name='paymentanalysis',
            name='risk_score',
            field=models.FloatField(help_text='Общая оценка риска (0-100)', null=True),
        ),
        migrations.AddIndex(
            model_name='paymentanalysis',
            index=models.Index(fields=['payment'], name='Analytics_p_payment_fabd56_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentanalysis',
            index=models.Index(fields=['analysis_timestamp'], name='Analytics_p_analysi_dd7c66_idx'),
        ),
    ]
