# Generated by Django 5.1.4 on 2025-04-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0007_alter_paymentanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentanalysis',
            name='analysis_date',
            field=models.DateField(auto_now=True),
        ),
    ]
