# Generated by Django 5.1.4 on 2025-04-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0008_paymentanalysis_analysis_date'),
        ('Order', '0009_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderanalytics',
            options={'verbose_name': 'Анализ заказа', 'verbose_name_plural': 'Аналитика заказов'},
        ),
        migrations.RemoveField(
            model_name='orderanalytics',
            name='time_performance',
        ),
        migrations.AlterField(
            model_name='orderanalytics',
            name='acquisition_source',
            field=models.CharField(help_text='Источник привлечения клиента', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderanalytics',
            name='customer_journey',
            field=models.JSONField(default=dict, help_text='Данные о пути клиента'),
        ),
        migrations.AlterField(
            model_name='orderanalytics',
            name='item_metrics',
            field=models.JSONField(default=dict, help_text='Метрики товарной корзины'),
        ),
        migrations.AlterField(
            model_name='orderanalytics',
            name='margin',
            field=models.DecimalField(decimal_places=2, help_text='Маржинальность заказа', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderanalytics',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='Order.order'),
        ),
        migrations.AlterField(
            model_name='orderanalytics',
            name='predicted_churn_risk',
            field=models.FloatField(help_text='Прогнозируемый риск оттока (%)', null=True),
        ),
        migrations.AddIndex(
            model_name='orderanalytics',
            index=models.Index(fields=['acquisition_source'], name='Analytics_o_acquisi_778c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderanalytics',
            index=models.Index(fields=['predicted_churn_risk'], name='Analytics_o_predict_6950b2_idx'),
        ),
    ]
