# Generated by Django 5.1.4 on 2025-04-06 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0010_stockhistory'),
        ('Order', '0009_alter_orderitem_product'),
        ('Product', '0009_product_cost_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryturnover',
            options={'verbose_name': 'Анализ оборачиваемости', 'verbose_name_plural': 'Аналитика оборачиваемости'},
        ),
        migrations.AlterModelOptions(
            name='orderitemanalytics',
            options={'verbose_name': 'Аналитика позиции заказа', 'verbose_name_plural': 'Аналитика позиций заказов'},
        ),
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'verbose_name': 'История запасов', 'verbose_name_plural': 'Истории запасов'},
        ),
        migrations.AddField(
            model_name='orderitemanalytics',
            name='delivery_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Срок доставки (дни)'),
        ),
        migrations.AddField(
            model_name='orderitemanalytics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='orderitemanalytics',
            name='popularity_score',
            field=models.FloatField(default=0.0, verbose_name='Индекс популярности'),
        ),
        migrations.AddField(
            model_name='orderitemanalytics',
            name='return_rate',
            field=models.FloatField(default=0.0, verbose_name='Процент возвратов'),
        ),
        migrations.AlterField(
            model_name='orderitemanalytics',
            name='cross_sell_products',
            field=models.ManyToManyField(to='Product.product', verbose_name='Сопутствующие товары'),
        ),
        migrations.AlterField(
            model_name='orderitemanalytics',
            name='margin',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Маржа'),
        ),
        migrations.AlterField(
            model_name='orderitemanalytics',
            name='order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='Order.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitemanalytics',
            name='profitability_index',
            field=models.FloatField(verbose_name='Индекс рентабельности (%)'),
        ),
        migrations.AddIndex(
            model_name='orderitemanalytics',
            index=models.Index(fields=['delivery_time'], name='Analytics_o_deliver_931218_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemanalytics',
            index=models.Index(fields=['popularity_score'], name='Analytics_o_popular_e90ae8_idx'),
        ),
    ]
