# Generated by Django 5.1.8 on 2025-04-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0011_alter_inventoryturnover_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productperformance',
            name='avg_selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='productperformance',
            name='discount_impact',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
