# Generated by Django 5.1.4 on 2025-03-19 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_usergroup_user_addres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'Группа пользователей', 'verbose_name_plural': 'Группы пользователей'},
        ),
        migrations.AddField(
            model_name='usergroup',
            name='description',
            field=models.TextField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='name',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usergroup',
            name='permissions',
            field=models.TextField(default='0', max_length=512),
        ),
        migrations.CreateModel(
            name='UserGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_add', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Элемент группы',
                'verbose_name_plural': 'Элементы групп',
            },
        ),
    ]
