# Generated by Django 5.1.4 on 2025-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_rename_addres_user_addresss'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Покупатель'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='customer', max_length=20),
        ),
    ]
