# Generated by Django 5.1.4 on 2025-03-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_user_currency_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addresss',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='', max_length=256),
        ),
    ]
