# Generated by Django 5.1.4 on 2025-03-23 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_order_user'),
        ('Payment', '0003_payment_processed_at_alter_payment_cost_and_more'),
        ('Product', '0007_alter_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='promotion_name',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-date', 'status'], name='Order_order_date_a1109c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'discount'], name='Order_order_product_ec1b86_idx'),
        ),
    ]
