# Generated by Django 5.1.4 on 2025-03-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_orderitem_promotion_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='quanity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promotion_type',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
