# Generated by Django 5.1.8 on 2025-04-15 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_alter_orderitem_product'),
        ('Payment', '0007_payment_needs_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Payment.payment'),
        ),
    ]
