# Generated by Django 5.1.4 on 2025-01-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('page_name', models.CharField(max_length=64)),
            ],
        ),
    ]
