# Generated by Django 5.1.4 on 2025-03-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_alter_pagetext_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagetext',
            options={'verbose_name': 'Текст страницы', 'verbose_name_plural': 'Тексты страниц'},
        ),
    ]
