# Generated by Django 5.1.4 on 2025-03-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_cart_quanity'),
        ('User', '0011_alter_usergroup_options_usergroup_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(max_length=100)),
                ('description', models.TextField(default='Base', max_length=512)),
                ('name', models.CharField(default='Base', max_length=64)),
                ('on_start', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.usergroup')),
            ],
            options={
                'verbose_name': 'Акция для группы',
                'verbose_name_plural': 'Акции для групп',
            },
        ),
    ]
