# Generated by Django 5.1.8 on 2025-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_rename_discription_subscription_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_end',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_start',
            field=models.FloatField(default=0.0),
        ),
    ]
