# Generated by Django 5.1.4 on 2025-03-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('method', models.TextField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('pay_time', models.DateTimeField(null=True)),
                ('cost', models.IntegerField()),
                ('payment_id', models.CharField(max_length=128)),
                ('discount', models.FloatField()),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
