# Generated by Django 5.1.4 on 2025-04-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
