# Generated by Django 5.1.4 on 2025-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
