# Generated by Django 5.1.4 on 2025-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_alter_payment_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20),
        ),
    ]
