# Generated by Django 5.1.4 on 2025-04-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_alter_payment_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
